spring.application.name=backendSpring
# Configuration OAuth2 pour Google
spring.security.oauth2.client.registration.google.client-id=35048312944-uv2upkrj7dq4o0nojtgb343q110rc4b4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google
# Fournisseur OAuth2 Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
rentalcars.allowed-origins=localhost:3000,localhost:8888
server.port=8080
rentalcars.exposed-headers=Origin,Content-Type", Accept,Authorization,Access-Control-Allow-origin,Access-Control-Allow-Credentials
rentalcars.allowed-headers=Origin,Content-Type,Accept,Authorization,Origin, Accept,X-Requested-with,Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-origin,Access-Control-Allow-Credentials
spring.datasource.url=jdbc:mysql://localhost:3306/cars-location
spring.datasource.username=root
spring.jpa.generate-ddl=true
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# App Properties
rentalcars.app.jwtSecret=WTbjX/KnfomT4xgtFz05iU/0sH8wk03niv4YSi9ATgz+fWdZ5FMGT7TZJOPMb1nXbKSe3i36JHgHHp8SExiUZw==
rentalcars.app.jwtExpirationMs=86400000
rentalcars.app.refreshTokenExpirationMs=86400000

stripe.api.key=sk_test_51Qa4URJ0GcGDS8zCz7G6D4SGxTqjWPKWMlIOZHEozZRoeTe6lw7ko4Ay3s19mqbWWQBEAFgwDHlZDS5bLpZBmRxu00pqbYKd5r